### ISSUE TITLE
On mobile, show share options in bottom bar

### ISSUE THREAD

**Issue by estevanmaito** [estevanmaito/sharect#10]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Sharect doesn't work on mobile now because on those systems when you select text, the OS already creates a tooltip. It's possible to still give the user the options to share, but it must be done in another, maybe without a tooltip.

**Describe alternatives you've considered**
The image below shows a common approach that websites give users to share the entire article.
![bottom share navigation](https://jquery-plugins.net/image/plugin/responsive-social-share-for-mobile-jquery.jpg)

The idea is really the same.

**Comment by estevanmaito** [comment]
How to detect "mobile" safely? I mean, the iPad Pro uses iOS and behaves like a normal tablet, even though it has 12". Using breakpoints could show the bottom bar in desktop browsers in some cases and it isn't future proof.

**Comment by Daksh14** [comment]
http://detectmobilebrowsers.com/ why not try this?

**Comment by estevanmaito** [comment]
> http://detectmobilebrowsers.com/ why not try this?

Thank you. I've looked into this solution but found some problems with it: 
1. it weighs almost the same as Sharect
2. it uses Regex to look for device and browser names, so it's not future proof

But it made me change my approach. Instead of looking for "mobile", I think we need to think of touch devices. Usually, a PC's primary input is mouse, so if the current device doesn't have a mouse as primary input, then we should not show the tooltip. This also solves the problem with desktops with touch and mouse. This solution would use the [Pointer Events API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events).

BUT, as it isn't widely [supported](https://caniuse.com/#feat=pointer) (mostly by Safari), a fallback would be to use the deprecated [window.orientation](https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation), still supported by those devices.

I'll keep the debate open while I make some tests.

**Comment by Daksh14** [comment]
Okay, btw I added transitions and added some responsiveness, If you have some time, please do check my pull request. :)
