### ISSUE TITLE
Sharect in WordPress

### ISSUE THREAD

**Issue by nektobit** [estevanmaito/sharect#26]
Hi Estevan
I have long wanted to make a simple wp plugin and place it in the worldpress directory.
https://github.com/nektobit/wp-sharect
How do you like this idea? Naturally, I can support users who have problems with the wordpress side.
If you think that you should not use your library this way, I will delete the repository without question :)

**Comment by estevanmaito** [comment]
Feel free to use it!
[Here is the license](https://github.com/estevanmaito/sharect/blob/master/LICENSE)
