### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by Minaxi11** [estevanmaito/sharect#29]
is it mobile responsive?

**Comment by estevanmaito** [comment]
It is responsive, but don't work on mobile, as it's impossible to overwrite the default text selection behavior.

For a while it was part of Sharect (see #10 ), but it was impossible to use as it would open the tooltip to share with Sharect AND the native bottom bar with dozens of options.

Mobile users are already well served and there is no plan to duplicate this feature using Sharect.
