### ISSUE TITLE
Enable this plugin only on given element or id or class not on body

### ISSUE THREAD

**Issue by mramitkumar-bapu** [estevanmaito/sharect#8]
This plugin do not work for a given particular id or class or  html element. or  am I missing something.

Say I wan to enable this plugin only on div having id say id1 but not on id having value id2 etc. same is true for class as well.

Would you suggest, how to achieve that.

**Comment by estevanmaito** [comment]
Solved in the latest release https://github.com/estevanmaito/sharect/releases/tag/v1.1.0

The documentation for the new (extended) API can be found here https://github.com/estevanmaito/sharect#docs
